global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'asm-bots'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

# Alert rules
rules:
  - name: HighLatency
    rules:
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High response time (instance {{ $labels.instance }})
          description: "95th percentile of response time is above 500ms"

      - alert: ErrorRateHigh
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High error rate (instance {{ $labels.instance }})
          description: "Error rate is above 1% for the last 5 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage (instance {{ $labels.instance }})
          description: "Memory usage is above 90%"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage (instance {{ $labels.instance }})
          description: "CPU usage is above 80%"

      - alert: LowCacheHitRate
        expr: rate(cache_hits_total[5m]) / (rate(cache_hits_total[5m]) + rate(cache_misses_total[5m])) < 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Low cache hit rate (instance {{ $labels.instance }})
          description: "Cache hit rate is below 80%"

      - alert: DatabaseSlowQueries
        expr: rate(database_slow_queries_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Slow database queries detected (instance {{ $labels.instance }})
          description: "Database queries taking longer than threshold detected"

      - alert: WebSocketDisconnections
        expr: rate(websocket_disconnections_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High WebSocket disconnection rate (instance {{ $labels.instance }})
          description: "WebSocket disconnections are above normal rate"