/**
 * `bun run roster-images` writes packages/bots/src/images.gen.ts: what each roster bot assembles
 * to (its `%name`, `%author`, `%strategy`, `%version`, and machine code in base64), so a page can
 * fight the roster with neither the assembler nor the sources (`rosterImage`). Run it after a
 * change to a roster file, the assembler, or the codec. `--check` writes nothing and exits 1 when
 * the file is not what it would write; `packages/bots/test/images.test.ts` runs that check in
 * `bun test`.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadRoster, ROSTER } from '../packages/bots/src/index'

/** The generated module. */
export const IMAGES_FILE = fileURLToPath(
  new URL('../packages/bots/src/images.gen.ts', import.meta.url),
)

/** Biome's line width (biome.json). */
const LINE_WIDTH = 100

/**
 * A string literal as Biome writes it: single quotes, unless the text has more single quotes than
 * double ones.
 */
export function literal(text: string): string {
  const singles = text.split("'").length - 1
  const doubles = text.split('"').length - 1
  const quote = singles > doubles ? '"' : "'"
  const escaped = text.replace(/\\/g, '\\\\').split(quote).join(`\\${quote}`)
  return `${quote}${escaped}${quote}`
}

/** An object key as Biome writes it: bare when it is an identifier. */
const key = (slug: string) => (/^[A-Za-z_$][\w$]*$/.test(slug) ? slug : literal(slug))

/** The text of images.gen.ts for the roster as it assembles now. */
export function imagesModule(): string {
  const roster = loadRoster()
  const rows = ROSTER.map(({ slug }) => {
    const bot = roster.get(slug)
    if (bot === undefined) throw new Error(`loadRoster has no bot '${slug}'`)
    const { name, author, strategy, version, bytes, diagnostics } = bot.assembled
    if (diagnostics.some((d) => d.severity === 'error')) {
      throw new Error(`roster bot '${slug}' does not assemble`)
    }
    const fields = Object.entries({
      name,
      author,
      strategy,
      version,
      bytes: Buffer.from(bytes).toString('base64'),
    }).map(([field, value]) => {
      const line = `    ${field}: ${literal(value)},`
      // Past the line width, Biome puts the value on a line of its own.
      return line.length <= LINE_WIDTH ? line : `    ${field}:\n      ${literal(value)},`
    })
    return `  ${key(slug)}: {\n${fields.join('\n')}\n  },`
  })
  return `// Generated by \`bun run roster-images\` (scripts/roster-images.ts) from the roster's sources.
// Do not edit: packages/bots/test/images.test.ts fails when this is not what they assemble to.

/** A roster bot's assembly: its metadata, and its machine code in base64. */
export interface RosterImageData {
  readonly name: string
  readonly author: string
  readonly strategy: string
  readonly version: string
  readonly bytes: string
}

/** Each roster bot's assembly, by slug. */
export const ROSTER_IMAGE_DATA: Readonly<Record<string, RosterImageData>> = {
${rows.join('\n')}
}
`
}

/** Writes the module to `file`, or with `check` compares `file` with it. Returns the exit code. */
export function rosterImages(
  check: boolean,
  log: (line: string) => void = console.log,
  file: string = IMAGES_FILE,
): number {
  const text = imagesModule()
  const path = relative(process.cwd(), file)
  if (!check) {
    writeFileSync(file, text)
    log(`wrote ${path}: ${ROSTER.length} bots`)
    return 0
  }
  if (readFileSync(file, 'utf8') === text) {
    log(`${path} is up to date`)
    return 0
  }
  log(`${path} is stale: run \`bun run roster-images\``)
  return 1
}

if (import.meta.main) {
  const args = process.argv.slice(2)
  if (args.some((a) => a !== '--check')) {
    console.error('usage: bun run roster-images [--check]')
    process.exit(2)
  }
  process.exit(rosterImages(args.includes('--check')))
}
